# Generated by Django 4.1.5 on 2023-01-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_watchlist_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='abour',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplatform'),
        ),
    ]
