# Generated by Django 4.1.5 on 2023-01-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='watchlist',
            new_name='watch_list',
        ),
    ]
