# Generated by Django 4.0.3 on 2023-01-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_reviews_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
