# Generated by Django 4.0.3 on 2023-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_reviews_avg_rating_reviews_number_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='number_rating',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
